# Generated by Django 3.2.7 on 2025-04-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20250403_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'Table Number'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name_plural': 'Accepted/Not'},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Title',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='ISBN',
            new_name='OrderNumber',
        ),
    ]
