# Generated by Django 3.2.7 on 2025-04-03 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_rename_ordernumber_book_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Id',
            new_name='ID',
        ),
    ]
