# Generated by Django 3.2.7 on 2025-04-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_rename_id_book_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Title',
            new_name='Id',
        ),
    ]
