# Generated by Django 3.2.7 on 2025-04-03 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_rename_title_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ISBN',
            new_name='OrderNo',
        ),
    ]
