# Generated by Django 3.2.7 on 2025-04-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_rename_isbn_book_orderno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='TableNo',
        ),
    ]
