# Generated by Django 3.2.7 on 2025-04-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_rename_orderno_book_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Id',
            new_name='Title',
        ),
    ]
