# Generated by Django 3.2.7 on 2025-04-03 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_rename_id_book_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TableNo',
            new_name='Author',
        ),
    ]
