# Generated by Django 3.2.7 on 2025-04-03 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_rename_tableno_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='TableNo',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Title',
            new_name='Id',
        ),
    ]
